import streamlit as st
import pandas as pd
import os

st.set_page_config(page_title="Production Dashboard", layout="wide")

# Path to the file generated by your main script
file_path = 'Waterjet Efficiency LU.xlsx'

if os.path.exists(file_path):
    st.title("🏭 Waterjet Production Dashboard")
    
    # --- TAB 1: Key Takeaways ---
    tab1, tab2, tab3 = st.tabs(["📊 Takeaways", "🧶 Beam Status", "📦 Beam Stock"])
    
    with tab1:
        df = pd.read_excel(file_path, sheet_name='Key Takeaways')
        st.dataframe(df, use_container_width=True)
        
    with tab2:
        df_beam = pd.read_excel(file_path, sheet_name='Beam Status')
        st.table(df_beam)

    with tab3:
        df_stock = pd.read_excel(file_path, sheet_name='Beam Stock')
        st.dataframe(df_stock, use_container_width=True)
else:
    st.error("Data file not found. Run the automation script first.")